In [1]:
import numpy as np
dataset_filename = "affinity_dataset.txt"
X = np.loadtxt(dataset_filename)

In [2]:
n_samples, n_features = X.shape
print("This dataset has {0} samples and {1} features".format(n_samples, n_features))
print(X[:5])

This dataset has 100 samples and 5 features
[[0. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 1.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1.]]


In [3]:
features = ["bread","milk","cheese","apples","bananas"]

In [4]:
# 사과를 구입한 사람의 수
num_apple_purchases = 0

for sample in X:
    if sample[3] == 1:  #This person bought apples
        num_apple_purchases += 1
print("{0} people bought Apples".format(num_apple_purchases))

43 people bought Apples


In [5]:
# 얼마나 많은 경우에 사과를 산 사람이 바나나도 샀는가?
# 규칙이 유효한 경우와 그렇지 안은 경우 모두 기록

rule_valid = 0   # 규칙이 유효
rule_invalid = 0  # 규칙이 비유효
for sample in X:
    if sample[3] == 1:     # this person bought Apples
        if sample[4] == 1:
            # this person bought both Apples and Bananas (규칙이 유효한 경우를 +1 counting)
            rule_valid += 1
        else:
            # this person bought Apples, but not Bananas (규칙이 비유효한 경우를 +1 counting)
            rule_invalid += 1
print("{0} cases of the rule being valid were discovered".format(rule_valid))
print("{0} cases of the rule being invalid were discovered".format(rule_invalid))


27 cases of the rule being valid were discovered
16 cases of the rule being invalid were discovered


In [6]:
# support(규칙이 발견된 횟수)와 confidence를 계산하기 위한 정보가 모두 존재하므로 계산
# the support is the number of times the rule is discovered
support = rule_valid

# rule_valid(이 규칙이 발견된 횟수) / num_apple_purchases(전제(사과를 산사람)에 해당하는 샘플 개수)
confidence = rule_valid / float(num_apple_purchases)
print("The support is {0} and the confidence is {1:.3f}.".format(support, confidence))

# confidence can be thought of as a percentage using the following{}
print("As a percentage, that is {0:.1f}%".format(100*confidence))

The support is 27 and the confidence is 0.628.
As a percentage, that is 62.8%
